/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedControlRouteImport } from './routes/_authenticated/control'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmployerRouteImport } from './routes/_authenticated/employer'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPostJobRouteImport } from './routes/_authenticated/post-job'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSalaryRouteImport } from './routes/_authenticated/salary'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AdminCandidatesRouteImport } from './routes/admin/candidates'
import { Route as AdminCompanyProfileRouteImport } from './routes/admin/company-profile'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminInterviewsRouteImport } from './routes/admin/interviews'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as CompanyCompanyIdRouteImport } from './routes/company.$companyId'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as SuperadminActivityLogsRouteImport } from './routes/superadmin/activity-logs'
import { Route as SuperadminAdminsRouteImport } from './routes/superadmin/admins'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin/dashboard'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin/login'
import { Route as SuperadminUsersRouteImport } from './routes/superadmin/users'
import { Route as UserApplicationsRouteImport } from './routes/user/applications'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as UserLoginRouteImport } from './routes/user/login'
import { Route as UserNotificationsRouteImport } from './routes/user/notifications'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserRegisterRouteImport } from './routes/user/register'
import { Route as UserResumeRouteImport } from './routes/user/resume'
import { Route as UserSavedJobsRouteImport } from './routes/user/saved-jobs'
import { Route as UserSettingsRouteImport } from './routes/user/settings'
import { Route as WorkersIndexRouteImport } from './routes/workers.index'
import { Route as WorkersWorkerIdRouteImport } from './routes/workers.$workerId'
import { Route as AuthenticatedControlEmployersRouteImport } from './routes/_authenticated/control.employers'
import { Route as AuthenticatedControlJobsRouteImport } from './routes/_authenticated/control.jobs'
import { Route as AuthenticatedControlLanguagesRouteImport } from './routes/_authenticated/control.languages'
import { Route as AuthenticatedControlReportsRouteImport } from './routes/_authenticated/control.reports'
import { Route as AuthenticatedControlSalaryRouteImport } from './routes/_authenticated/control.salary'
import { Route as AuthenticatedControlSettingsRouteImport } from './routes/_authenticated/control.settings'
import { Route as AuthenticatedControlUsersRouteImport } from './routes/_authenticated/control.users'
import { Route as AuthenticatedEmployerApplicantsRouteImport } from './routes/_authenticated/employer.applicants'
import { Route as AuthenticatedEmployerEmployeesRouteImport } from './routes/_authenticated/employer.employees'
import { Route as AuthenticatedEmployerJobsRouteImport } from './routes/_authenticated/employer.jobs'
import { Route as AuthenticatedEmployerReportsRouteImport } from './routes/_authenticated/employer.reports'
import { Route as AuthenticatedEmployerSalaryRouteImport } from './routes/_authenticated/employer.salary'
import { Route as AdminJobsCreateRouteImport } from './routes/admin/jobs.create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControlRoute = AuthenticatedControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployerRoute = AuthenticatedEmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostJobRoute = AuthenticatedPostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalaryRoute = AuthenticatedSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompanyProfileRoute = AdminCompanyProfileRouteImport.update({
  id: '/company-profile',
  path: '/company-profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInterviewsRoute = AdminInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const CompanyCompanyIdRoute = CompanyCompanyIdRouteImport.update({
  id: '/company/$companyId',
  path: '/company/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminActivityLogsRoute = SuperadminActivityLogsRouteImport.update({
  id: '/superadmin/activity-logs',
  path: '/superadmin/activity-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminAdminsRoute = SuperadminAdminsRouteImport.update({
  id: '/superadmin/admins',
  path: '/superadmin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/superadmin/dashboard',
  path: '/superadmin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/superadmin/login',
  path: '/superadmin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminUsersRoute = SuperadminUsersRouteImport.update({
  id: '/superadmin/users',
  path: '/superadmin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UserApplicationsRoute = UserApplicationsRouteImport.update({
  id: '/user/applications',
  path: '/user/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLoginRoute = UserLoginRouteImport.update({
  id: '/user/login',
  path: '/user/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserNotificationsRoute = UserNotificationsRouteImport.update({
  id: '/user/notifications',
  path: '/user/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRegisterRoute = UserRegisterRouteImport.update({
  id: '/user/register',
  path: '/user/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UserResumeRoute = UserResumeRouteImport.update({
  id: '/user/resume',
  path: '/user/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSavedJobsRoute = UserSavedJobsRouteImport.update({
  id: '/user/saved-jobs',
  path: '/user/saved-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/user/settings',
  path: '/user/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersWorkerIdRoute = WorkersWorkerIdRouteImport.update({
  id: '/workers/$workerId',
  path: '/workers/$workerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedControlEmployersRoute =
  AuthenticatedControlEmployersRouteImport.update({
    id: '/employers',
    path: '/employers',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlJobsRoute =
  AuthenticatedControlJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlLanguagesRoute =
  AuthenticatedControlLanguagesRouteImport.update({
    id: '/languages',
    path: '/languages',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlReportsRoute =
  AuthenticatedControlReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlSalaryRoute =
  AuthenticatedControlSalaryRouteImport.update({
    id: '/salary',
    path: '/salary',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlSettingsRoute =
  AuthenticatedControlSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlUsersRoute =
  AuthenticatedControlUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedEmployerApplicantsRoute =
  AuthenticatedEmployerApplicantsRouteImport.update({
    id: '/applicants',
    path: '/applicants',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerEmployeesRoute =
  AuthenticatedEmployerEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerJobsRoute =
  AuthenticatedEmployerJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerReportsRoute =
  AuthenticatedEmployerReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerSalaryRoute =
  AuthenticatedEmployerSalaryRouteImport.update({
    id: '/salary',
    path: '/salary',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AdminJobsCreateRoute = AdminJobsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/control': typeof AuthenticatedControlRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/post-job': typeof AuthenticatedPostJobRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/salary': typeof AuthenticatedSalaryRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/company-profile': typeof AdminCompanyProfileRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/interviews': typeof AdminInterviewsRoute
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/superadmin/activity-logs': typeof SuperadminActivityLogsRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/user/applications': typeof UserApplicationsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/login': typeof UserLoginRoute
  '/user/notifications': typeof UserNotificationsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/register': typeof UserRegisterRoute
  '/user/resume': typeof UserResumeRoute
  '/user/saved-jobs': typeof UserSavedJobsRoute
  '/user/settings': typeof UserSettingsRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/control/employers': typeof AuthenticatedControlEmployersRoute
  '/control/jobs': typeof AuthenticatedControlJobsRoute
  '/control/languages': typeof AuthenticatedControlLanguagesRoute
  '/control/reports': typeof AuthenticatedControlReportsRoute
  '/control/salary': typeof AuthenticatedControlSalaryRoute
  '/control/settings': typeof AuthenticatedControlSettingsRoute
  '/control/users': typeof AuthenticatedControlUsersRoute
  '/employer/applicants': typeof AuthenticatedEmployerApplicantsRoute
  '/employer/employees': typeof AuthenticatedEmployerEmployeesRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsRoute
  '/employer/reports': typeof AuthenticatedEmployerReportsRoute
  '/employer/salary': typeof AuthenticatedEmployerSalaryRoute
  '/admin/jobs/create': typeof AdminJobsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/control': typeof AuthenticatedControlRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/post-job': typeof AuthenticatedPostJobRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/salary': typeof AuthenticatedSalaryRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/company-profile': typeof AdminCompanyProfileRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/interviews': typeof AdminInterviewsRoute
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/superadmin/activity-logs': typeof SuperadminActivityLogsRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/user/applications': typeof UserApplicationsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/login': typeof UserLoginRoute
  '/user/notifications': typeof UserNotificationsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/register': typeof UserRegisterRoute
  '/user/resume': typeof UserResumeRoute
  '/user/saved-jobs': typeof UserSavedJobsRoute
  '/user/settings': typeof UserSettingsRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/jobs': typeof JobsIndexRoute
  '/workers': typeof WorkersIndexRoute
  '/control/employers': typeof AuthenticatedControlEmployersRoute
  '/control/jobs': typeof AuthenticatedControlJobsRoute
  '/control/languages': typeof AuthenticatedControlLanguagesRoute
  '/control/reports': typeof AuthenticatedControlReportsRoute
  '/control/salary': typeof AuthenticatedControlSalaryRoute
  '/control/settings': typeof AuthenticatedControlSettingsRoute
  '/control/users': typeof AuthenticatedControlUsersRoute
  '/employer/applicants': typeof AuthenticatedEmployerApplicantsRoute
  '/employer/employees': typeof AuthenticatedEmployerEmployeesRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsRoute
  '/employer/reports': typeof AuthenticatedEmployerReportsRoute
  '/employer/salary': typeof AuthenticatedEmployerSalaryRoute
  '/admin/jobs/create': typeof AdminJobsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/control': typeof AuthenticatedControlRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/post-job': typeof AuthenticatedPostJobRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/salary': typeof AuthenticatedSalaryRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/company-profile': typeof AdminCompanyProfileRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/interviews': typeof AdminInterviewsRoute
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/superadmin/activity-logs': typeof SuperadminActivityLogsRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/user/applications': typeof UserApplicationsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/login': typeof UserLoginRoute
  '/user/notifications': typeof UserNotificationsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/register': typeof UserRegisterRoute
  '/user/resume': typeof UserResumeRoute
  '/user/saved-jobs': typeof UserSavedJobsRoute
  '/user/settings': typeof UserSettingsRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/_authenticated/control/employers': typeof AuthenticatedControlEmployersRoute
  '/_authenticated/control/jobs': typeof AuthenticatedControlJobsRoute
  '/_authenticated/control/languages': typeof AuthenticatedControlLanguagesRoute
  '/_authenticated/control/reports': typeof AuthenticatedControlReportsRoute
  '/_authenticated/control/salary': typeof AuthenticatedControlSalaryRoute
  '/_authenticated/control/settings': typeof AuthenticatedControlSettingsRoute
  '/_authenticated/control/users': typeof AuthenticatedControlUsersRoute
  '/_authenticated/employer/applicants': typeof AuthenticatedEmployerApplicantsRoute
  '/_authenticated/employer/employees': typeof AuthenticatedEmployerEmployeesRoute
  '/_authenticated/employer/jobs': typeof AuthenticatedEmployerJobsRoute
  '/_authenticated/employer/reports': typeof AuthenticatedEmployerReportsRoute
  '/_authenticated/employer/salary': typeof AuthenticatedEmployerSalaryRoute
  '/admin/jobs/create': typeof AdminJobsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/faq'
    | '/home'
    | '/reset-password'
    | '/unauthorized'
    | '/applications'
    | '/control'
    | '/dashboard'
    | '/employer'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/salary'
    | '/admin/applications'
    | '/admin/candidates'
    | '/admin/company-profile'
    | '/admin/dashboard'
    | '/admin/interviews'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/company/$companyId'
    | '/jobs/$jobId'
    | '/superadmin/activity-logs'
    | '/superadmin/admins'
    | '/superadmin/dashboard'
    | '/superadmin/login'
    | '/superadmin/users'
    | '/user/applications'
    | '/user/dashboard'
    | '/user/login'
    | '/user/notifications'
    | '/user/profile'
    | '/user/register'
    | '/user/resume'
    | '/user/saved-jobs'
    | '/user/settings'
    | '/workers/$workerId'
    | '/jobs/'
    | '/workers/'
    | '/control/employers'
    | '/control/jobs'
    | '/control/languages'
    | '/control/reports'
    | '/control/salary'
    | '/control/settings'
    | '/control/users'
    | '/employer/applicants'
    | '/employer/employees'
    | '/employer/jobs'
    | '/employer/reports'
    | '/employer/salary'
    | '/admin/jobs/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/faq'
    | '/home'
    | '/reset-password'
    | '/unauthorized'
    | '/applications'
    | '/control'
    | '/dashboard'
    | '/employer'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/salary'
    | '/admin/applications'
    | '/admin/candidates'
    | '/admin/company-profile'
    | '/admin/dashboard'
    | '/admin/interviews'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/company/$companyId'
    | '/jobs/$jobId'
    | '/superadmin/activity-logs'
    | '/superadmin/admins'
    | '/superadmin/dashboard'
    | '/superadmin/login'
    | '/superadmin/users'
    | '/user/applications'
    | '/user/dashboard'
    | '/user/login'
    | '/user/notifications'
    | '/user/profile'
    | '/user/register'
    | '/user/resume'
    | '/user/saved-jobs'
    | '/user/settings'
    | '/workers/$workerId'
    | '/jobs'
    | '/workers'
    | '/control/employers'
    | '/control/jobs'
    | '/control/languages'
    | '/control/reports'
    | '/control/salary'
    | '/control/settings'
    | '/control/users'
    | '/employer/applicants'
    | '/employer/employees'
    | '/employer/jobs'
    | '/employer/reports'
    | '/employer/salary'
    | '/admin/jobs/create'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/faq'
    | '/home'
    | '/reset-password'
    | '/unauthorized'
    | '/_authenticated/applications'
    | '/_authenticated/control'
    | '/_authenticated/dashboard'
    | '/_authenticated/employer'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/post-job'
    | '/_authenticated/profile'
    | '/_authenticated/salary'
    | '/admin/applications'
    | '/admin/candidates'
    | '/admin/company-profile'
    | '/admin/dashboard'
    | '/admin/interviews'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/company/$companyId'
    | '/jobs/$jobId'
    | '/superadmin/activity-logs'
    | '/superadmin/admins'
    | '/superadmin/dashboard'
    | '/superadmin/login'
    | '/superadmin/users'
    | '/user/applications'
    | '/user/dashboard'
    | '/user/login'
    | '/user/notifications'
    | '/user/profile'
    | '/user/register'
    | '/user/resume'
    | '/user/saved-jobs'
    | '/user/settings'
    | '/workers/$workerId'
    | '/jobs/'
    | '/workers/'
    | '/_authenticated/control/employers'
    | '/_authenticated/control/jobs'
    | '/_authenticated/control/languages'
    | '/_authenticated/control/reports'
    | '/_authenticated/control/salary'
    | '/_authenticated/control/settings'
    | '/_authenticated/control/users'
    | '/_authenticated/employer/applicants'
    | '/_authenticated/employer/employees'
    | '/_authenticated/employer/jobs'
    | '/_authenticated/employer/reports'
    | '/_authenticated/employer/salary'
    | '/admin/jobs/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HomeRoute: typeof HomeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  CompanyCompanyIdRoute: typeof CompanyCompanyIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  SuperadminActivityLogsRoute: typeof SuperadminActivityLogsRoute
  SuperadminAdminsRoute: typeof SuperadminAdminsRoute
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
  SuperadminLoginRoute: typeof SuperadminLoginRoute
  SuperadminUsersRoute: typeof SuperadminUsersRoute
  UserApplicationsRoute: typeof UserApplicationsRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserLoginRoute: typeof UserLoginRoute
  UserNotificationsRoute: typeof UserNotificationsRoute
  UserProfileRoute: typeof UserProfileRoute
  UserRegisterRoute: typeof UserRegisterRoute
  UserResumeRoute: typeof UserResumeRoute
  UserSavedJobsRoute: typeof UserSavedJobsRoute
  UserSettingsRoute: typeof UserSettingsRoute
  WorkersWorkerIdRoute: typeof WorkersWorkerIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control': {
      id: '/_authenticated/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof AuthenticatedControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer': {
      id: '/_authenticated/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof AuthenticatedEmployerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-job': {
      id: '/_authenticated/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof AuthenticatedPostJobRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary': {
      id: '/_authenticated/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof AuthenticatedSalaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/company-profile': {
      id: '/admin/company-profile'
      path: '/company-profile'
      fullPath: '/admin/company-profile'
      preLoaderRoute: typeof AdminCompanyProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/interviews': {
      id: '/admin/interviews'
      path: '/interviews'
      fullPath: '/admin/interviews'
      preLoaderRoute: typeof AdminInterviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/company/$companyId': {
      id: '/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof CompanyCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/activity-logs': {
      id: '/superadmin/activity-logs'
      path: '/superadmin/activity-logs'
      fullPath: '/superadmin/activity-logs'
      preLoaderRoute: typeof SuperadminActivityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/admins': {
      id: '/superadmin/admins'
      path: '/superadmin/admins'
      fullPath: '/superadmin/admins'
      preLoaderRoute: typeof SuperadminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/superadmin/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/login': {
      id: '/superadmin/login'
      path: '/superadmin/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/users': {
      id: '/superadmin/users'
      path: '/superadmin/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof SuperadminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/applications': {
      id: '/user/applications'
      path: '/user/applications'
      fullPath: '/user/applications'
      preLoaderRoute: typeof UserApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/login': {
      id: '/user/login'
      path: '/user/login'
      fullPath: '/user/login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/notifications': {
      id: '/user/notifications'
      path: '/user/notifications'
      fullPath: '/user/notifications'
      preLoaderRoute: typeof UserNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/register': {
      id: '/user/register'
      path: '/user/register'
      fullPath: '/user/register'
      preLoaderRoute: typeof UserRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/resume': {
      id: '/user/resume'
      path: '/user/resume'
      fullPath: '/user/resume'
      preLoaderRoute: typeof UserResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/saved-jobs': {
      id: '/user/saved-jobs'
      path: '/user/saved-jobs'
      fullPath: '/user/saved-jobs'
      preLoaderRoute: typeof UserSavedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/user/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/$workerId': {
      id: '/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId'
      preLoaderRoute: typeof WorkersWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/control/employers': {
      id: '/_authenticated/control/employers'
      path: '/employers'
      fullPath: '/control/employers'
      preLoaderRoute: typeof AuthenticatedControlEmployersRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/jobs': {
      id: '/_authenticated/control/jobs'
      path: '/jobs'
      fullPath: '/control/jobs'
      preLoaderRoute: typeof AuthenticatedControlJobsRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/languages': {
      id: '/_authenticated/control/languages'
      path: '/languages'
      fullPath: '/control/languages'
      preLoaderRoute: typeof AuthenticatedControlLanguagesRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/reports': {
      id: '/_authenticated/control/reports'
      path: '/reports'
      fullPath: '/control/reports'
      preLoaderRoute: typeof AuthenticatedControlReportsRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/salary': {
      id: '/_authenticated/control/salary'
      path: '/salary'
      fullPath: '/control/salary'
      preLoaderRoute: typeof AuthenticatedControlSalaryRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/settings': {
      id: '/_authenticated/control/settings'
      path: '/settings'
      fullPath: '/control/settings'
      preLoaderRoute: typeof AuthenticatedControlSettingsRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/users': {
      id: '/_authenticated/control/users'
      path: '/users'
      fullPath: '/control/users'
      preLoaderRoute: typeof AuthenticatedControlUsersRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/employer/applicants': {
      id: '/_authenticated/employer/applicants'
      path: '/applicants'
      fullPath: '/employer/applicants'
      preLoaderRoute: typeof AuthenticatedEmployerApplicantsRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/employees': {
      id: '/_authenticated/employer/employees'
      path: '/employees'
      fullPath: '/employer/employees'
      preLoaderRoute: typeof AuthenticatedEmployerEmployeesRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/jobs': {
      id: '/_authenticated/employer/jobs'
      path: '/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof AuthenticatedEmployerJobsRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/reports': {
      id: '/_authenticated/employer/reports'
      path: '/reports'
      fullPath: '/employer/reports'
      preLoaderRoute: typeof AuthenticatedEmployerReportsRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/salary': {
      id: '/_authenticated/employer/salary'
      path: '/salary'
      fullPath: '/employer/salary'
      preLoaderRoute: typeof AuthenticatedEmployerSalaryRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/admin/jobs/create': {
      id: '/admin/jobs/create'
      path: '/create'
      fullPath: '/admin/jobs/create'
      preLoaderRoute: typeof AdminJobsCreateRouteImport
      parentRoute: typeof AdminJobsRoute
    }
  }
}

interface AuthenticatedControlRouteChildren {
  AuthenticatedControlEmployersRoute: typeof AuthenticatedControlEmployersRoute
  AuthenticatedControlJobsRoute: typeof AuthenticatedControlJobsRoute
  AuthenticatedControlLanguagesRoute: typeof AuthenticatedControlLanguagesRoute
  AuthenticatedControlReportsRoute: typeof AuthenticatedControlReportsRoute
  AuthenticatedControlSalaryRoute: typeof AuthenticatedControlSalaryRoute
  AuthenticatedControlSettingsRoute: typeof AuthenticatedControlSettingsRoute
  AuthenticatedControlUsersRoute: typeof AuthenticatedControlUsersRoute
}

const AuthenticatedControlRouteChildren: AuthenticatedControlRouteChildren = {
  AuthenticatedControlEmployersRoute: AuthenticatedControlEmployersRoute,
  AuthenticatedControlJobsRoute: AuthenticatedControlJobsRoute,
  AuthenticatedControlLanguagesRoute: AuthenticatedControlLanguagesRoute,
  AuthenticatedControlReportsRoute: AuthenticatedControlReportsRoute,
  AuthenticatedControlSalaryRoute: AuthenticatedControlSalaryRoute,
  AuthenticatedControlSettingsRoute: AuthenticatedControlSettingsRoute,
  AuthenticatedControlUsersRoute: AuthenticatedControlUsersRoute,
}

const AuthenticatedControlRouteWithChildren =
  AuthenticatedControlRoute._addFileChildren(AuthenticatedControlRouteChildren)

interface AuthenticatedEmployerRouteChildren {
  AuthenticatedEmployerApplicantsRoute: typeof AuthenticatedEmployerApplicantsRoute
  AuthenticatedEmployerEmployeesRoute: typeof AuthenticatedEmployerEmployeesRoute
  AuthenticatedEmployerJobsRoute: typeof AuthenticatedEmployerJobsRoute
  AuthenticatedEmployerReportsRoute: typeof AuthenticatedEmployerReportsRoute
  AuthenticatedEmployerSalaryRoute: typeof AuthenticatedEmployerSalaryRoute
}

const AuthenticatedEmployerRouteChildren: AuthenticatedEmployerRouteChildren = {
  AuthenticatedEmployerApplicantsRoute: AuthenticatedEmployerApplicantsRoute,
  AuthenticatedEmployerEmployeesRoute: AuthenticatedEmployerEmployeesRoute,
  AuthenticatedEmployerJobsRoute: AuthenticatedEmployerJobsRoute,
  AuthenticatedEmployerReportsRoute: AuthenticatedEmployerReportsRoute,
  AuthenticatedEmployerSalaryRoute: AuthenticatedEmployerSalaryRoute,
}

const AuthenticatedEmployerRouteWithChildren =
  AuthenticatedEmployerRoute._addFileChildren(
    AuthenticatedEmployerRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedControlRoute: typeof AuthenticatedControlRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployerRoute: typeof AuthenticatedEmployerRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPostJobRoute: typeof AuthenticatedPostJobRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSalaryRoute: typeof AuthenticatedSalaryRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedControlRoute: AuthenticatedControlRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployerRoute: AuthenticatedEmployerRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPostJobRoute: AuthenticatedPostJobRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSalaryRoute: AuthenticatedSalaryRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminJobsRouteChildren {
  AdminJobsCreateRoute: typeof AdminJobsCreateRoute
}

const AdminJobsRouteChildren: AdminJobsRouteChildren = {
  AdminJobsCreateRoute: AdminJobsCreateRoute,
}

const AdminJobsRouteWithChildren = AdminJobsRoute._addFileChildren(
  AdminJobsRouteChildren,
)

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminCompanyProfileRoute: typeof AdminCompanyProfileRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInterviewsRoute: typeof AdminInterviewsRoute
  AdminJobsRoute: typeof AdminJobsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminCompanyProfileRoute: AdminCompanyProfileRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInterviewsRoute: AdminInterviewsRoute,
  AdminJobsRoute: AdminJobsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HomeRoute: HomeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  CompanyCompanyIdRoute: CompanyCompanyIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  SuperadminActivityLogsRoute: SuperadminActivityLogsRoute,
  SuperadminAdminsRoute: SuperadminAdminsRoute,
  SuperadminDashboardRoute: SuperadminDashboardRoute,
  SuperadminLoginRoute: SuperadminLoginRoute,
  SuperadminUsersRoute: SuperadminUsersRoute,
  UserApplicationsRoute: UserApplicationsRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserLoginRoute: UserLoginRoute,
  UserNotificationsRoute: UserNotificationsRoute,
  UserProfileRoute: UserProfileRoute,
  UserRegisterRoute: UserRegisterRoute,
  UserResumeRoute: UserResumeRoute,
  UserSavedJobsRoute: UserSavedJobsRoute,
  UserSettingsRoute: UserSettingsRoute,
  WorkersWorkerIdRoute: WorkersWorkerIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  WorkersIndexRoute: WorkersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
