/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPostJobRouteImport } from './routes/_authenticated/post-job'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSalaryRouteImport } from './routes/_authenticated/salary'
import { Route as CompanyCompanyIdRouteImport } from './routes/company.$companyId'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as WorkersIndexRouteImport } from './routes/workers.index'
import { Route as WorkersWorkerIdRouteImport } from './routes/workers.$workerId'
import { Route as AuthenticatedControlIndexRouteImport } from './routes/_authenticated/control.index'
import { Route as AuthenticatedControlEmployersRouteImport } from './routes/_authenticated/control.employers'
import { Route as AuthenticatedControlJobsRouteImport } from './routes/_authenticated/control.jobs'
import { Route as AuthenticatedControlLanguagesRouteImport } from './routes/_authenticated/control.languages'
import { Route as AuthenticatedControlReportsRouteImport } from './routes/_authenticated/control.reports'
import { Route as AuthenticatedControlSalaryRouteImport } from './routes/_authenticated/control.salary'
import { Route as AuthenticatedControlSettingsRouteImport } from './routes/_authenticated/control.settings'
import { Route as AuthenticatedControlUsersRouteImport } from './routes/_authenticated/control.users'
import { Route as AuthenticatedEmployerIndexRouteImport } from './routes/_authenticated/employer.index'
import { Route as AuthenticatedEmployerApplicantsRouteImport } from './routes/_authenticated/employer.applicants'
import { Route as AuthenticatedEmployerEmployeesRouteImport } from './routes/_authenticated/employer.employees'
import { Route as AuthenticatedEmployerJobsRouteImport } from './routes/_authenticated/employer.jobs'
import { Route as AuthenticatedEmployerReportsRouteImport } from './routes/_authenticated/employer.reports'
import { Route as AuthenticatedEmployerSalaryRouteImport } from './routes/_authenticated/employer.salary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostJobRoute = AuthenticatedPostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalaryRoute = AuthenticatedSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CompanyCompanyIdRoute = CompanyCompanyIdRouteImport.update({
  id: '/company/$companyId',
  path: '/company/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersWorkerIdRoute = WorkersWorkerIdRouteImport.update({
  id: '/workers/$workerId',
  path: '/workers/$workerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedControlIndexRoute =
  AuthenticatedControlIndexRouteImport.update({
    id: '/control/',
    path: '/control/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControlEmployersRoute =
  AuthenticatedControlEmployersRouteImport.update({
    id: '/control/employers',
    path: '/control/employers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControlJobsRoute =
  AuthenticatedControlJobsRouteImport.update({
    id: '/control/jobs',
    path: '/control/jobs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControlLanguagesRoute =
  AuthenticatedControlLanguagesRouteImport.update({
    id: '/control/languages',
    path: '/control/languages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControlReportsRoute =
  AuthenticatedControlReportsRouteImport.update({
    id: '/control/reports',
    path: '/control/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControlSalaryRoute =
  AuthenticatedControlSalaryRouteImport.update({
    id: '/control/salary',
    path: '/control/salary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControlSettingsRoute =
  AuthenticatedControlSettingsRouteImport.update({
    id: '/control/settings',
    path: '/control/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControlUsersRoute =
  AuthenticatedControlUsersRouteImport.update({
    id: '/control/users',
    path: '/control/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerIndexRoute =
  AuthenticatedEmployerIndexRouteImport.update({
    id: '/employer/',
    path: '/employer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerApplicantsRoute =
  AuthenticatedEmployerApplicantsRouteImport.update({
    id: '/employer/applicants',
    path: '/employer/applicants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerEmployeesRoute =
  AuthenticatedEmployerEmployeesRouteImport.update({
    id: '/employer/employees',
    path: '/employer/employees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerJobsRoute =
  AuthenticatedEmployerJobsRouteImport.update({
    id: '/employer/jobs',
    path: '/employer/jobs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerReportsRoute =
  AuthenticatedEmployerReportsRouteImport.update({
    id: '/employer/reports',
    path: '/employer/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerSalaryRoute =
  AuthenticatedEmployerSalaryRouteImport.update({
    id: '/employer/salary',
    path: '/employer/salary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/reset-password': typeof ResetPasswordRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/post-job': typeof AuthenticatedPostJobRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/salary': typeof AuthenticatedSalaryRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/control/employers': typeof AuthenticatedControlEmployersRoute
  '/control/jobs': typeof AuthenticatedControlJobsRoute
  '/control/languages': typeof AuthenticatedControlLanguagesRoute
  '/control/reports': typeof AuthenticatedControlReportsRoute
  '/control/salary': typeof AuthenticatedControlSalaryRoute
  '/control/settings': typeof AuthenticatedControlSettingsRoute
  '/control/users': typeof AuthenticatedControlUsersRoute
  '/employer/applicants': typeof AuthenticatedEmployerApplicantsRoute
  '/employer/employees': typeof AuthenticatedEmployerEmployeesRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsRoute
  '/employer/reports': typeof AuthenticatedEmployerReportsRoute
  '/employer/salary': typeof AuthenticatedEmployerSalaryRoute
  '/control/': typeof AuthenticatedControlIndexRoute
  '/employer/': typeof AuthenticatedEmployerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/reset-password': typeof ResetPasswordRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/post-job': typeof AuthenticatedPostJobRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/salary': typeof AuthenticatedSalaryRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/jobs': typeof JobsIndexRoute
  '/workers': typeof WorkersIndexRoute
  '/control/employers': typeof AuthenticatedControlEmployersRoute
  '/control/jobs': typeof AuthenticatedControlJobsRoute
  '/control/languages': typeof AuthenticatedControlLanguagesRoute
  '/control/reports': typeof AuthenticatedControlReportsRoute
  '/control/salary': typeof AuthenticatedControlSalaryRoute
  '/control/settings': typeof AuthenticatedControlSettingsRoute
  '/control/users': typeof AuthenticatedControlUsersRoute
  '/employer/applicants': typeof AuthenticatedEmployerApplicantsRoute
  '/employer/employees': typeof AuthenticatedEmployerEmployeesRoute
  '/employer/jobs': typeof AuthenticatedEmployerJobsRoute
  '/employer/reports': typeof AuthenticatedEmployerReportsRoute
  '/employer/salary': typeof AuthenticatedEmployerSalaryRoute
  '/control': typeof AuthenticatedControlIndexRoute
  '/employer': typeof AuthenticatedEmployerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/post-job': typeof AuthenticatedPostJobRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/salary': typeof AuthenticatedSalaryRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/_authenticated/control/employers': typeof AuthenticatedControlEmployersRoute
  '/_authenticated/control/jobs': typeof AuthenticatedControlJobsRoute
  '/_authenticated/control/languages': typeof AuthenticatedControlLanguagesRoute
  '/_authenticated/control/reports': typeof AuthenticatedControlReportsRoute
  '/_authenticated/control/salary': typeof AuthenticatedControlSalaryRoute
  '/_authenticated/control/settings': typeof AuthenticatedControlSettingsRoute
  '/_authenticated/control/users': typeof AuthenticatedControlUsersRoute
  '/_authenticated/employer/applicants': typeof AuthenticatedEmployerApplicantsRoute
  '/_authenticated/employer/employees': typeof AuthenticatedEmployerEmployeesRoute
  '/_authenticated/employer/jobs': typeof AuthenticatedEmployerJobsRoute
  '/_authenticated/employer/reports': typeof AuthenticatedEmployerReportsRoute
  '/_authenticated/employer/salary': typeof AuthenticatedEmployerSalaryRoute
  '/_authenticated/control/': typeof AuthenticatedControlIndexRoute
  '/_authenticated/employer/': typeof AuthenticatedEmployerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/faq'
    | '/reset-password'
    | '/applications'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/salary'
    | '/company/$companyId'
    | '/jobs/$jobId'
    | '/workers/$workerId'
    | '/jobs/'
    | '/workers/'
    | '/control/employers'
    | '/control/jobs'
    | '/control/languages'
    | '/control/reports'
    | '/control/salary'
    | '/control/settings'
    | '/control/users'
    | '/employer/applicants'
    | '/employer/employees'
    | '/employer/jobs'
    | '/employer/reports'
    | '/employer/salary'
    | '/control/'
    | '/employer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/faq'
    | '/reset-password'
    | '/applications'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/salary'
    | '/company/$companyId'
    | '/jobs/$jobId'
    | '/workers/$workerId'
    | '/jobs'
    | '/workers'
    | '/control/employers'
    | '/control/jobs'
    | '/control/languages'
    | '/control/reports'
    | '/control/salary'
    | '/control/settings'
    | '/control/users'
    | '/employer/applicants'
    | '/employer/employees'
    | '/employer/jobs'
    | '/employer/reports'
    | '/employer/salary'
    | '/control'
    | '/employer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/faq'
    | '/reset-password'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/post-job'
    | '/_authenticated/profile'
    | '/_authenticated/salary'
    | '/company/$companyId'
    | '/jobs/$jobId'
    | '/workers/$workerId'
    | '/jobs/'
    | '/workers/'
    | '/_authenticated/control/employers'
    | '/_authenticated/control/jobs'
    | '/_authenticated/control/languages'
    | '/_authenticated/control/reports'
    | '/_authenticated/control/salary'
    | '/_authenticated/control/settings'
    | '/_authenticated/control/users'
    | '/_authenticated/employer/applicants'
    | '/_authenticated/employer/employees'
    | '/_authenticated/employer/jobs'
    | '/_authenticated/employer/reports'
    | '/_authenticated/employer/salary'
    | '/_authenticated/control/'
    | '/_authenticated/employer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CompanyCompanyIdRoute: typeof CompanyCompanyIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  WorkersWorkerIdRoute: typeof WorkersWorkerIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-job': {
      id: '/_authenticated/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof AuthenticatedPostJobRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary': {
      id: '/_authenticated/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof AuthenticatedSalaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/company/$companyId': {
      id: '/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof CompanyCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/$workerId': {
      id: '/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId'
      preLoaderRoute: typeof WorkersWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/control/': {
      id: '/_authenticated/control/'
      path: '/control'
      fullPath: '/control/'
      preLoaderRoute: typeof AuthenticatedControlIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control/employers': {
      id: '/_authenticated/control/employers'
      path: '/control/employers'
      fullPath: '/control/employers'
      preLoaderRoute: typeof AuthenticatedControlEmployersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control/jobs': {
      id: '/_authenticated/control/jobs'
      path: '/control/jobs'
      fullPath: '/control/jobs'
      preLoaderRoute: typeof AuthenticatedControlJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control/languages': {
      id: '/_authenticated/control/languages'
      path: '/control/languages'
      fullPath: '/control/languages'
      preLoaderRoute: typeof AuthenticatedControlLanguagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control/reports': {
      id: '/_authenticated/control/reports'
      path: '/control/reports'
      fullPath: '/control/reports'
      preLoaderRoute: typeof AuthenticatedControlReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control/salary': {
      id: '/_authenticated/control/salary'
      path: '/control/salary'
      fullPath: '/control/salary'
      preLoaderRoute: typeof AuthenticatedControlSalaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control/settings': {
      id: '/_authenticated/control/settings'
      path: '/control/settings'
      fullPath: '/control/settings'
      preLoaderRoute: typeof AuthenticatedControlSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control/users': {
      id: '/_authenticated/control/users'
      path: '/control/users'
      fullPath: '/control/users'
      preLoaderRoute: typeof AuthenticatedControlUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/': {
      id: '/_authenticated/employer/'
      path: '/employer'
      fullPath: '/employer/'
      preLoaderRoute: typeof AuthenticatedEmployerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/applicants': {
      id: '/_authenticated/employer/applicants'
      path: '/employer/applicants'
      fullPath: '/employer/applicants'
      preLoaderRoute: typeof AuthenticatedEmployerApplicantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/employees': {
      id: '/_authenticated/employer/employees'
      path: '/employer/employees'
      fullPath: '/employer/employees'
      preLoaderRoute: typeof AuthenticatedEmployerEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/jobs': {
      id: '/_authenticated/employer/jobs'
      path: '/employer/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof AuthenticatedEmployerJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/reports': {
      id: '/_authenticated/employer/reports'
      path: '/employer/reports'
      fullPath: '/employer/reports'
      preLoaderRoute: typeof AuthenticatedEmployerReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/salary': {
      id: '/_authenticated/employer/salary'
      path: '/employer/salary'
      fullPath: '/employer/salary'
      preLoaderRoute: typeof AuthenticatedEmployerSalaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPostJobRoute: typeof AuthenticatedPostJobRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSalaryRoute: typeof AuthenticatedSalaryRoute
  AuthenticatedControlEmployersRoute: typeof AuthenticatedControlEmployersRoute
  AuthenticatedControlJobsRoute: typeof AuthenticatedControlJobsRoute
  AuthenticatedControlLanguagesRoute: typeof AuthenticatedControlLanguagesRoute
  AuthenticatedControlReportsRoute: typeof AuthenticatedControlReportsRoute
  AuthenticatedControlSalaryRoute: typeof AuthenticatedControlSalaryRoute
  AuthenticatedControlSettingsRoute: typeof AuthenticatedControlSettingsRoute
  AuthenticatedControlUsersRoute: typeof AuthenticatedControlUsersRoute
  AuthenticatedEmployerApplicantsRoute: typeof AuthenticatedEmployerApplicantsRoute
  AuthenticatedEmployerEmployeesRoute: typeof AuthenticatedEmployerEmployeesRoute
  AuthenticatedEmployerJobsRoute: typeof AuthenticatedEmployerJobsRoute
  AuthenticatedEmployerReportsRoute: typeof AuthenticatedEmployerReportsRoute
  AuthenticatedEmployerSalaryRoute: typeof AuthenticatedEmployerSalaryRoute
  AuthenticatedControlIndexRoute: typeof AuthenticatedControlIndexRoute
  AuthenticatedEmployerIndexRoute: typeof AuthenticatedEmployerIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPostJobRoute: AuthenticatedPostJobRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSalaryRoute: AuthenticatedSalaryRoute,
  AuthenticatedControlEmployersRoute: AuthenticatedControlEmployersRoute,
  AuthenticatedControlJobsRoute: AuthenticatedControlJobsRoute,
  AuthenticatedControlLanguagesRoute: AuthenticatedControlLanguagesRoute,
  AuthenticatedControlReportsRoute: AuthenticatedControlReportsRoute,
  AuthenticatedControlSalaryRoute: AuthenticatedControlSalaryRoute,
  AuthenticatedControlSettingsRoute: AuthenticatedControlSettingsRoute,
  AuthenticatedControlUsersRoute: AuthenticatedControlUsersRoute,
  AuthenticatedEmployerApplicantsRoute: AuthenticatedEmployerApplicantsRoute,
  AuthenticatedEmployerEmployeesRoute: AuthenticatedEmployerEmployeesRoute,
  AuthenticatedEmployerJobsRoute: AuthenticatedEmployerJobsRoute,
  AuthenticatedEmployerReportsRoute: AuthenticatedEmployerReportsRoute,
  AuthenticatedEmployerSalaryRoute: AuthenticatedEmployerSalaryRoute,
  AuthenticatedControlIndexRoute: AuthenticatedControlIndexRoute,
  AuthenticatedEmployerIndexRoute: AuthenticatedEmployerIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CompanyCompanyIdRoute: CompanyCompanyIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  WorkersWorkerIdRoute: WorkersWorkerIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  WorkersIndexRoute: WorkersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
